services:
  mongo:
    image: mongo
    container_name: my-mongo-for-civil-guruji
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_civil_guruji_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

volumes:
  mongo_civil_guruji_volume:
    driver: local