enum ErrorCodesEnum{
    INVALID_ID="INVALID_ID",
    NOT_FOUND="NOT_FOUND",
    SERVER_ERROR="SERVER_ERROR",
    INVALID_DATA_FORMAT="INVALID_DATA_FORMAT",
    DUPLICATE_RECORD="DUPLICATE_RECORD"
}

export default ErrorCodesEnum;