enum UserTypeEnum{
    ADMIN="ADMIN",
    SALES_MANAGER="SALES_MANAGER",
    SALES_EXECUTIVE="SALES_EXECUTIVE",
    READ_ONLY_USER="READ_ONLY_USER",
    MARKETTING_MANAGER="MARKETTING_MANAGER",
    CUSTOMER_SUPPORT="CUSTOMER_SUPPORT"
}

export default UserTypeEnum;